image: node:latest

variables:
  NPM_CONFIG_UNSAFE_PERM: "true"

before_script:
  - npm config set cache $CI_PROJECT_DIR/.npm
  - npm ci

cache:
  paths:
  - .npm

stages:
  - test
  - release

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm i --no-save rxjs
    - npm test -- --coverage

publish:
  stage: release
  except:
    - tags
  script:
    - npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
    - npx semantic-release
