image: node:latest

variables:
  NPM_CONFIG_UNSAFE_PERM: "true"

before_script:
  - npm config set cache $CI_PROJECT_DIR/.npm
  - npm ci
  - node -v
  - npm -v

cache:
  paths:
  - .npm

stages:
  - test
  - release

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm i --no-save rxjs
    - npm test -- --coverage
